LICENSE
=> adding LICENSE file

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/chrome/content/browser.js
@spacifici We get the search extension id from **js** and use messages to pass it to **java** side
=> get search extension id

Dockerfile
This Dockerfile will also be used for Continuous Deployment using Fastlane.
=> Added installation of Ruby and Fastlane in the Dockerfile

README.md, mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/toolbar/ToolbarEditText.java, mozilla-release/mobile/android/chrome/content/browser.js
To make it work you need an extension compiled from https://github.com/spacifici/navigation-extension/tree/fennec_search
=> Search integration

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/chrome/content/browser.js
=> Basic search integration

mozilla-release/mobile/android/app/src/main/res/layout/gecko_app.xml, mozilla-release/mobile/android/app/src/photon/res/color/tabs_counter_fg.xml, mozilla-release/mobile/android/app/src/photon/res/color/tabs_counter_text.xml, mozilla-release/mobile/android/app/src/photon/res/color/url_bar_image_color.xml, mozilla-release/mobile/android/app/src/photon/res/layout/toolbar_display_layout.xml, mozilla-release/mobile/android/app/src/photon/res/values/colors.xml
@spacifici  lets discuss with alina & inci more about how the things should look like.
=> AB2-27: change url bar to blue and icons to white

mozconfigs/cliqz-alpha.mozconfig, mozconfigs/cliqz.mozconfig, mozilla-release/mobile/android/app/src/main/res/xml/preferences.xml, mozilla-release/mobile/android/app/src/main/res/xml/preferences_general.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferenceFragment.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in, mozilla-release/mobile/android/branding/cliqz-alpha/locales/en-US/brand.dtd, mozilla-release/mobile/android/branding/cliqz/locales/en-US/brand.dtd
to spare time I combined the PRs on one PR with requested changes.
AB2-49: add Report Website
AB2-51: add tips and tricks to the settings menu
AB2-52: replacing Mozile Fennce (FAQ, about, Feedback) with FAQ & Support Cliqz
=> AB2:49.51.52

mozilla-release/mobile/android/chrome/content/browser.js
=> AB2-69: Notify android browser regarding the number of trackers blocked

mozilla-release/mobile/android/chrome/content/browser.js
=> AB2-92: Bridge control center data from privacy extension to native

mozilla-release/mobile/android/app/src/main/res/values/arrays.xml, mozilla-release/mobile/android/app/src/main/res/xml/preferences_general.xml, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in
this commit contain these tickets:
- AB2-72
- AB2-73
- AB2-74
- AB2-75
- AB2-89
- AB2-94
=> AB2-71:add search, browsing category to general settings menu

mozilla-release/mobile/android/app/src/main/res/xml/preferences_general.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/activitystream/homepanel/ActivityStreamHomeFragment.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/activitystream/homepanel/ActivityStreamPanel.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/activitystream/homepanel/StreamRecyclerAdapter.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/home/HomePager.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in
this PR contains:
AB2-76
AB2-77
AB2-78
=> AB2-71: add Show background, topsite, news to general settings menu

mozilla-release/mobile/android/app/src/main/res/values/arrays.xml, mozilla-release/mobile/android/app/src/main/res/xml/preferences.xml, mozilla-release/mobile/android/app/src/main/res/xml/preferences_privacy.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in
this PR includes:
- AB2-113
- AB2-114
- AB2-115
=> AB2-103:add clear  data category to privacy settings menu

mozilla-release/mobile/android/app/src/main/res/xml/preferences_general.xml, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in
it's just the preference.
I will port the dialog when porting the Youtube downloader.
=> AB2-84: add download options category to settings menu

mozilla-release/mobile/android/app/src/main/res/xml/preferences_general.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/home/MyOffrzPanel.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/myoffrz/MyOffrzUtils.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferenceFragment.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/PreferenceManager.java, mozilla-release/mobile/android/base/locales/en-US/android_strings.dtd, mozilla-release/mobile/android/base/strings.xml.in
=> AB2-85: add show hints to general settings menu

mozilla-release/mobile/android/components/extensions/ext-android.js, mozilla-release/mobile/android/components/extensions/ext-history.js, mozilla-release/mobile/android/components/extensions/jar.mn, mozilla-release/mobile/android/components/extensions/schemas/history.json, mozilla-release/mobile/android/components/extensions/schemas/jar.mn
@spacifici @khaled-cliqz @chrmod 
@spacifici can you please check if the current format can be filled from native?
=> AB2-159: Add history search for Android WebExtensions API

mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java
This reverts commit 65b35c1dac6fcbe1a4a48565db4175abc4f8709c.
=> Revert "AB2-122: remove advanced settings from settings menu (#75)"

mozilla-release/mobile/android/base/locales/en-US/cliqz_strings.dtd
=> Added Strings for Translations

Jenkinsfile.nightly
=> Nightly Improvements and fixes

Jenkinsfile.nightly
=> Fix nightly build

Jenkinsfile
Now, only the APK will be archived by the Jenkins Job.
=> Fixed the part where the job was archiving the whole folder

mozilla-release/mobile/android/chrome/content/browser.js
Extension will be asynchronously updating search engines through
the experimental api
=> Don't push default search engine to extension

Jenkinsfile.nightly
@ravjit-cliqz Needed for nightly to work.
=> Fix failing nightly

Jenkinsfile.docker
This should fix the requirement of not finding gcc-6 and gc++-6 while building the Android App.
=> Setting HOST_CC and HOST_CXX in mozconfig

mozilla-release/mobile/android/base/java/org/mozilla/gecko/controlcenter/OverviewFragment.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/controlcenter/SiteTrackersListAdapter.java
=> AB2-224  Changes on the site trackers view does not affect the Blocked numbers

mozilla-release/mobile/android/app/src/photon/res/color/url_bar_title.xml
=> AB2-266 Fix user query not visible while typing

mozilla-release/mobile/android/chrome/content/browser.js
=> Search: speed up the loading

Jenkinsfile.nightly, Jenkinsfile.upload, mozilla-release/mobile/android/app/build.gradle, mozilla-release/mobile/android/fastlane/Appfile, mozilla-release/mobile/android/fastlane/Fastfile
=> Publishing of apks to the playstore

mozilla-release/Makefile.in, mozilla-release/config/privacy.txt
=> use full_path for the privacy extension

mozilla-release/mobile/android/app/src/main/res/layout/ghostery_overview_fragment.xml
Before After screenshots
<p float="left">
</p>
=> AB2-312 Center buttons content in control center

Jenkinsfile.uploadcliqz, Jenkinsfile.uploadghostery
=> AB2-359 Separate playstore upload AB2-358 Use ghostery upload key

mozilla-release/config/search.txt
This upgrade includes:
- Read app channel from native
- Cards layout fixes
- Extension ready signal to android
- Support landscape in cards
=> Upgrade extension version to 1.29.1_mobile_pre3

Jenkinsfile.nightly, Jenkinsfile.uploadcliqz, Jenkinsfile.uploadghostery, mozconfigs/jenkins.mozconfig
@joseph-cliqz Please have a look.
=> Add l10n support for Nightly and Deployment builds

mozilla-release/mobile/android/base/java/org/mozilla/gecko/GeckoApplication.java
=> Remove MultiDex

mozilla-release/mobile/android/app/src/main/res/color/action_bar_secondary_menu_item_colors.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/menu/MenuItemDefault.java
=> AB2-334 Two different disabled menu buttons have slightly different colors

mozilla-release/mobile/android/base/java/org/mozilla/gecko/tabs/TabsPanelThumbnailView.java
=> AB2-175-2 Tabs Overview Rebranding; Fix crash: use older api for older version

mozilla-release/config/search.txt
This upgrade includes:
- Fix of default search engine for webextensions
- Fix for getting the channel from native
- AppConstants is now sync
=> Upgrade extension to 1.30 master

mozilla-release/mobile/locales/searchplugins/ddg.xml, mozilla-release/mobile/locales/searchplugins/google-2018.xml, mozilla-release/mobile/locales/searchplugins/google.xml
=> use custom search parameters for mobile users

mozilla-release/mobile/android/app/src/main/res/layout/tabs_panel_default.xml, mozilla-release/mobile/android/app/src/photon/res/layout/private_tabs_panel.xml
With help from Inci, added a ghostery mask logo and made the background black.
=> AB2-415-2 Add ghostery mask logo in private tabs description

mozilla-release/mobile/android/components/extensions/ext-utils.js
=> AB2-433: Close any open extension popups when Privacy control center is triggered

mozilla-release/mobile/android/app/mobile.js
@spacifici we should do a more detailed check on the prefs
=> disable snippets & system addon updates

mozilla-release/mobile/android/app/mobile.js
=> override the UA on google SERPs for a better user experience

mozilla-release/mobile/android/app/src/main/res/layout/home_combined_history_panel.xml, mozilla-release/mobile/android/app/src/main/res/layout/home_empty_panel.xml, mozilla-release/mobile/android/app/src/photon/res/values/dimens.xml, mozilla-release/mobile/android/base/java/org/mozilla/gecko/home/HomeAdapter.java
=> AB2-401 Overlay transitions between the pager screens is not seamed anymore

mozilla-release/config/privacy.txt
=> Update Privacy extension to 8.2.4

mozilla-release/mobile/android/chrome/content/browser.js
=> Privacy extension hook - change the policy from native

mozilla-release/config/privacy.txt
@eleniS can you please confirm that this XPI disables offers ?
=> Update Privacy extension to 8.2.6

mozilla-release/config/privacy.txt
=> Update privacy extension to 8.2.8

Dockerfile
Also set the correct NDK_HOME.
=> Using rust-v1.28.0 as default.

Dockerfile
Extracting create another child directory. So fixing it.
=> NDK Home fix

mozilla-release/config/search.txt, mozilla-release/mobile/android/chrome/content/browser.js
@spacifici I also made the change to browser.js to match the module and action names on the extension part
=> Update extension to 3.30.5 to get backend countries

mozilla-release/config/privacy.txt
@zhonghao-cliqz @remusao @spacifici
=> Update privacy extension - adblocker speedup

mozilla-release/mobile/android/app/src/photon/java/org/mozilla/gecko/toolbar/ToolbarDisplayLayout.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/toolbar/PageActionLayout.java
=> AB2-319:show AddToHomeScreen onboarding after the button appears

mozilla-release/config/privacy.txt, mozilla-release/config/search.txt
Previous privacy extension was not signed.
Previous search extension had a critical bug and it was not loading correctly.
=> Extensions version bump

Dockerfile, mozconfigs/deploy.mozconfig
=> Update Docker machine

mozilla-release/mobile/android/components/extensions/ext-android.js
=> import history API using the geckoview path

mozilla-release/mobile/android/base/java/org/mozilla/gecko/onboarding/CliqzIntroPagerAdapter.java, mozilla-release/mobile/android/chrome/content/browser.js, mozilla-release/mobile/android/standard/java/org/mozilla/gecko/controlcenter/GlobalTrackersFragment.java, mozilla-release/mobile/android/standard/java/org/mozilla/gecko/controlcenter/RestoreDefaultsDialog.java
@spacifici @ravjit-cliqz we should only merge this after https://github.com/ghostery/ghostery-extension/pull/223 is merged and we start using a newer version for the privacy extension
=> Privacy extension uplift adaptations

mozilla-release/mobile/android/base/java/org/mozilla/gecko/distribution/Distribution.java, mozilla-release/mobile/android/chrome/content/browser.js
Delete the extensions inside the profile in order to use the system addons packaged within the browser
@spacifici
=> Use the system addons packaged within the browser

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/chrome/content/browser.js
=> Improve first search experience

mozilla-release/config/search.txt, mozilla-release/mobile/android/chrome/content/browser.js
Interesting! I can not add a WIP label :-)
Please don't merge yet. Once https://github.com/cliqz/navigation-extension/pull/7012/ is finished and merged, I'll update extension version and we can merge this one as well.
=> EX-8275: change theme based on private mode

mozilla-release/config/privacy.txt
contains performance improvements and production bundle
=> privacy extension version bump

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/GeckoApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/telemetry/TelemetryPreferences.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/telemetry/pingbuilders/TelemetryCorePingBuilder.java, mozilla-release/mobile/android/chrome/content/browser.js, mozilla-release/modules/libpref/init/all.js
=> Telemetry: add landings metric

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/antiphishing/AntiPhishingUtils.java
@jayesh-cliqz @zhonghao-cliqz @spacifici
=> AntiPhishing: handle special cases like about:XXX

mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java
=> Telemetry: use the right prefs for storing the number of landings

Dockerfile, Jenkinsfile.ad-hoc, freshtab/.gitignore, freshtab/index.js, freshtab/package-lock.json, freshtab/package.json, freshtab/rn-cli.config.js, mozilla-release/.gitignore, mozilla-release/build.gradle, mozilla-release/mobile/android/app/build.gradle, mozilla-release/mobile/android/app/src/main/res/menu/cliqz_browser_app_menu.xml, mozilla-release/mobile/android/app/src/main/res/xml/preferences_advanced.xml, mozilla-release/mobile/android/base/AndroidManifest.xml.in, mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java
Under `freshtab` branch we are going to experiment with react-native to figure out:
* is it suitable platform for fast prototyping of new tab features
* what is it performance/startup cost
This PR, sets up minimalistic configuration for ad-hoc builds only.
IMPORTANT: Those changes should not land on `master` until investigations are finished.
=> Setting up Freshtab experiment

Jenkinsfile.ad-hoc, Jenkinsfile.nightly
=> Move nightly builds to kria

mozilla-release/config/search.txt
new version reduces startup time by:
* disabling resource compression
* replacing mathjs library with much smaller alternative
=> search extension version bump

Dockerfile, Jenkinsfile, Jenkinsfile.artifact, Jenkinsfile.docker
- Use Custom Docker Base
- Remove our Gradle Cache
=> Docker fixes

mozilla-release/mobile/android/app/mobile.js
=> Limit UA override to google SERP only

Dockerfile
@chrmod @spacifici Fix for the ad-hoc builds that are failing.
=> Fix permission issue when building docker image on kria

.gitignore, mozilla-release/mobile/android/base/java/com/cliqz/SystemAddon.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/chrome/content/browser.js
new class provides the way to ask for AB tests and send telemetry
=> Simplified messaging bus from native to system addon 

mozilla-release/mobile/android/chrome/content/browser.js
=> AB2-825 default backend: country has priority over language

cliqz/package-lock.json, cliqz/package.json, mozilla-release/mobile/android/base/java/com/cliqz/react/BridgePackage.java, mozilla-release/mobile/android/base/java/com/cliqz/react/SearchBackground.java, mozilla-release/mobile/android/base/java/com/cliqz/react/modules/LocaleConstantsModule.java, mozilla-release/mobile/android/base/java/com/cliqz/react/modules/SearchEnginesModule.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/preferences/SearchPreferenceCategory.java, mozilla-release/mobile/android/chrome/content/browser.js
please don't squash on merge - this PR includes indentetion fixes for browser.js
=> React native search engines

vars/jira.groovy
=> Change regular expression to match the issue ids better

cliqz/package-lock.json, cliqz/package.json, mozilla-release/mobile/android/base/java/com/cliqz/react/modules/BrowserActionsModule.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/AboutPages.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/Tabs.java, mozilla-release/mobile/android/base/java/org/mozilla/gecko/toolbar/ToolbarEditLayout.java, mozilla-release/mobile/android/chrome/content/browser.js
requires: https://github.com/cliqz/navigation-extension/pull/7768
=> AB2-566 Trampoline Implementation

Jenkinsfile.nightlyadhoc
Right now the job will only publish to ghostery-canary playstore account.
=> AB2-967 Homogenize nightly and publish jobs

mozilla-release/mobile/android/base/java/com/cliqz/react/SearchUI.java
I fixed based on the solution provided here https://github.com/facebook/react-native/issues/14533.
I was not able to reproduce
=> Fix View.NO_ID error

mozilla-release/mobile/android/chrome/content/browser.js
changing the format to match the schema
=> CLIQZ_ADDON_VERSION telemetry fix

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm
https://hg.mozilla.org/releases/mozilla-release/rev/848b15028562c6757748070f637e0e4f0bbb5f65
required to resolve: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
=> Fix: install new cert for addons
